test_framework:
    # Assumes this image has already been built using our Dockerfile
    # we do it this way because we want the build context to be the
    # user's test repository, and we are buried inside node_modules.
    image: selenium_test_runner
    environment:
        BROWSER:
        ENV:
        RESULTS_DIR:
    volumes:
        - "${TESTS_DIR}:/test/test"
        - "${PAGEOBJECTS_DIR}:/test/pageobjects"
        - "${RESULTS_DIR}:/test/results"
    links:
        - hub
    command: /test/scripts/run-tests.sh
# Selenium grid set up. Note that the selenium hub seems to require that it
# be called 'hub' in order for the client browser containers to link correctly.
hub:
  image: selenium/hub
  ports:
    - "4444"
chrome:
  image: selenium/node-chrome
  links:
    - hub
